trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - MasterDetailTabbed/*

stages:
- stage: masterDetailTabbed
  displayName: Build MasterDetailPage with TabbedPage Sample
  
  jobs:
  - template: build/masterdetail-tabbed-android.yml
  - template: build/masterdetail-tabbed-ios.yml